export default {
	allowedRegions: ["eu" , "na", "ru"],
	defaultRegionParamOverride: "eu",
	apiUrl: "http://localhost:8080",
	filesUrl: "http://localhost:8080/static/",
	gameClasses: ["Warrior", "Lancer", "Slayer", "Berserker", "Sorcerer", "Archer", "Priest", "Mystic", "Reaper", "Gunner", "Brawler", "Ninja", "Valkyrie"],
	tanksGameClasses: ["Lancer", "Warrior", "Brawler", "Berserker"],
	healersGameClasses: ["Priest", "Mystic"],
	allowedDungeons: [],
	windowTitle: "Tera DPS",
	windowTitleSearchTop: "[Tera DPS] Leaderboard",
	windowTitleSearch: "[Tera DPS] Search",
	windowTitleAbout: "",
	windowTitleApi: "",
	windowTitleDetails: "[Tera DPS] Run details",
};